---
title: "Fleet Maker"
author: "Nate Lant"
date: "3/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Read in the nodes and select the coordinates at random.
Then convert the coorinates to epsg:26912 (meters)

## Data and conversion

```{r}
# nodes
nodes <- read_csv("R/data/nodes.csv")
# max ridehail vehicle ids is 500
wavs <- 16
cars <- 50
n <- wavs+cars

mySample <- nodes %>% 
  sample_n(n) %>%
  transmute(
    myId = 1:n,
    initialLocationX = xcoord,
    initialLocationY = ycoord
  )

```


## Generate new file

```{r}
ids <- read_csv("test/input_new/small_mix/ridehailfleet_wav.csv") 

idTable <- ids %>% transmute(myId = row_number(), id) 

table <- left_join(mySample, idTable) %>% 
  transmute(
    id, 
    rideHailManagerId = "GlobalRHM",
    vehicleType = ifelse(myId > wavs, "Car", "WAV"),
    initialLocationX, 
    initialLocationY,
    shifts = "{10:25200};{25300:80000}",
    geofenceX = NA,
    geofenceY = NA,
    geofenceRadius = NA
  )

write_csv(table, "test/input_new/small_mix/fleet_16.csv")

```

