---
title: "ModeChoice Calibration Using Events File"
author: "Chris Day"
date: "11/4/2021"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
events2.0 <- read_csv("events/0.events.csv", col_types = cols(.default = "c")) %>%
  filter(type == "ModeChoice") %>%
  group_by(mode) %>%
  select(person, tourIndex, tourPurpose, mode,currentTourMode, income, vehicleOwnership, availableAlternatives, personalVehicleAvailable, length, time, type) %>%
  arrange(person)

modalsplits <- events2.0 %>%
  group_by(mode) %>% 
  summarise(cnt = n()) %>%
  mutate(pct = cnt / sum(cnt) * 100,iter = 1)

eventsTrip1 <- events2.0 %>% filter(tourIndex == 1)
eventstest <- events2.0  %>% filter(mode %in% c("hov2","hov3","hov2_teleportation","hov3_teleportation","car")) %>%
  filter(mode != currentTourMode)

hovsplits <- eventsTrip1 %>%
  group_by(mode) %>%
  filter(mode %in% c("hov2","hov3","hov2_teleportation","hov3_teleportation")) %>%
  summarise(cnt = n()) %>%
  mutate(pct = cnt / sum(cnt) * 100,iter = 1)

ggplot(hovsplits) + 
  aes(x = iter,y = pct, fill = mode) + 
  ggtitle("Modal Split by Tour Purpose") +
  geom_bar(position="dodge", stat="identity") + theme_bw()
  scale_fill_brewer(palette = "Pastel2")

```

