---
title: "Wheelchair Mini Analysis"
author: "Nate Lant"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xml2)
library(XML)
library(Hmisc)
```

## Reading in the data

```{r}
# events file
# comes from agentsim, more to do with agents
# the physsimevents.xml is more about the vehilces (used in Via)
events <- read_csv("output/wc_mini/wav_1/ITERS/it.0/0.events.csv.gz") # FILE

# wc person ids
wc_ids <- read_csv("R/data/persons_wc_mini.csv") %>%
  mutate(wc_var = "TRUE")

# wav vehicle ids test/input/sf-light/rideHailFleet_wav.csv # input (FILE)
# output/wc_mini/run_1/ITERS/it.0/0.rideHailFleet.csv.gz # output (PROCEDURAL)
wavs <- read_csv("test/input/sf-light/rideHailFleet_wav.csv") %>%
  filter(vehicleType == "WAV-rh-only")

# write_csv(wavs, "R/data/wav_ids.csv")

non_wavs <- read_csv("test/input/sf-light/rideHailFleet_wav.csv") %>%
  filter(vehicleType != "WAV-rh-only")
```

## WC population behavior

Which vehicles are being used by WC people? how many times? for how long?

```{r}
events %>% filter(person == "010100-2012000596480-0-179582")
# eventually get wc person events
# what modes are they using?

# create trips file of wc users
population_events <- events %>%
  filter(person %in% wc_ids$ids) %>%
  select(time, person, type, vehicle) %>%
  group_by(person) %>%
  mutate(travel_time = ifelse(type=="PersonLeavesVehicle" & vehicle==lag(vehicle), time - lag(time), NA)) %>% arrange(person)

```


```{r}
# Which vehicles are being used by WC people? how many times? for how long?
# travel time is in seconds
population_events %>% 
  mutate(trip = ifelse(!is.na(travel_time), 1, NA)) %>%
  group_by(vehicle) %>%
  summarise(n = n(),
            trips = sum(trip, na.rm = T),
            mean_tt = mean(travel_time, na.rm = T),
            sd_tt = sd(travel_time, na.rm = T),
            max_tt = max(travel_time, na.rm = T))
# join on vehicle type 
# mutate(mode = case_when(vehicle %in% wav$ids ~ "WAV", vehicle %in% rh$ids ~ "rh"))
```



## WAV stats

Which people are using WAVs?

```{r}
# are the wavs in the output
events %>% filter(str_detect(vehicle, "WAV"))
```


```{r}
# just look at wav events
vehicles_events <- events %>%
  filter(vehicle %in% wavs$id) %>%
  select(time, vehicle, type, person) %>% 
  group_by(person) %>%
  mutate(travel_time = ifelse(type=="PersonLeavesVehicle" & vehicle==lag(vehicle), time - lag(time), NA),
         trip = ifelse(!is.na(travel_time), 1, NA) ) %>% 
  ungroup() %>%
  arrange(vehicle)
```

```{r}
# which people are using WAVs
vehicles_events %>% 
  group_by(person) %>%
  summarise(n = n(),
            trips = sum(trip, na.rm = T),
            mean_tt = mean(travel_time, na.rm = T),
            sd_tt = sd(travel_time, na.rm = T),
            max_tt = max(travel_time, na.rm = T)) %>%
  mutate(wc_var = ifelse(person %in% wc_ids$ids, T, F))
```


## Ride hail (regular) stats

Which people are using ride hail?

```{r}
# 
rh_events <- events %>%
  filter(vehicle %in% non_wavs$id) %>%
  select(time, vehicle, type, person) %>% 
  group_by(person) %>%
  mutate(travel_time = ifelse(type=="PersonLeavesVehicle" & vehicle==lag(vehicle), time - lag(time), NA),
         trip = ifelse(!is.na(travel_time), 1, NA) ) %>% 
  ungroup() %>%
  arrange(vehicle)
```

```{r}
# which people are using ride hail
rh_events %>% 
  group_by(person) %>%
  summarise(n = n(),
            trips = sum(trip, na.rm = T),
            mean_tt = mean(travel_time, na.rm = T),
            sd_tt = sd(travel_time, na.rm = T),
            max_tt = max(travel_time, na.rm = T)) %>%
  mutate(wc_var = ifelse(person %in% wc_ids$ids, T, F)) 
# sort by WC to make things easier?
# arrange(wc_var)?
```